apiVersion: v2
appVersion: "1.0"
description: DDD CQRS boilerplate
name: symfony-5-es-cqrs-boilerplate
version: 0.1.0
type: application
dependencies:
  - name: rabbitmq
    version: 12.4.1
    repository: https://charts.bitnami.com/bitnami
    conditions: rabbitmq.selfHosted
  - name: traefik
    version: 1.87.7
    repository: https://charts.helm.sh/stable/
    conditions: traefik.selfHosted
  - name: mysql
    version: 9.14.3
    repository: https://charts.bitnami.com/bitnami
    conditions: mysql.selfHosted
  - name: elasticsearch
    version: 19.13.8
    repository: https://charts.bitnami.com/bitnami
    conditions: elasticsearch.selfHosted
